# frontend-pipeline.yml
trigger:
  branches:
    include:
      - deploy
    exclude:
      - main
  paths:
    include:
      - frontend/**
    exclude:
      - backend/**

pr: none

jobs:
  - job: Build
    pool:
      vmImage: "windows-latest"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "22.x"
        displayName: "Install Node.js 22"

      - script: npm install
        displayName: "Npm Install"
        workingDirectory: "frontend"

      # --- BUILD ---
      - script: npx vite build
        displayName: "Vite Build"
        workingDirectory: "frontend"

      - task: ArchiveFiles@2
        displayName: "Zip Dist"
        inputs:
          rootFolderOrFile: "frontend/dist"
          includeRootFolder: false
          archiveType: "zip"
          archiveFile: "$(Build.ArtifactStagingDirectory)/frontend.zip"

      # Publish zip
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: frontend_pkgs

  - deployment: DeployToIIS
    dependsOn: Build
    environment:
      name: "Win16a"
      resourceName: "WIN16A"
      resourceType: virtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: frontend_pkgs

            # Deploy to wwwroot-uat
            - task: IISWebAppDeploymentOnMachineGroup@0
              displayName: "Deploy to wwwroot-uat"
              inputs:
                WebSiteName: "TallyJv4-UAT"
                Package: "$(Pipeline.Workspace)/frontend_pkgs/frontend.zip"
                TakeAppOfflineFlag: true
                VirtualApplication: "wwwroot-uat"

            # Deploy to wwwroot-prod
            - task: IISWebAppDeploymentOnMachineGroup@0
              displayName: "Deploy to wwwroot-prod"
              inputs:
                WebSiteName: "TallyJv4-UAT"
                Package: "$(Pipeline.Workspace)/frontend_pkgs/frontend.zip"
                TakeAppOfflineFlag: false # No need to take app offline for a non-active folder
                VirtualApplication: "wwwroot-prod"
