# frontend-pipeline.yml
trigger:
  branches:
    include:
      - deploy
    exclude:
      - main
  paths:
    include:
      - frontend/**
    exclude:
      - backend/**

pr: none

jobs:
  - job: Build
    pool:
      vmImage: "windows-latest"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "22.x"
        displayName: "Install Node.js 22"

      - script: npm install
        displayName: "Npm Install"
        workingDirectory: "frontend"

      # --- UAT BUILD ---
      - script: npx vite build --mode uat
        displayName: "Vite Build: UAT"
        workingDirectory: "frontend"

      - task: ArchiveFiles@2
        displayName: "Zip UAT Dist"
        inputs:
          rootFolderOrFile: "frontend/dist"
          includeRootFolder: false
          archiveType: "zip"
          archiveFile: "$(Build.ArtifactStagingDirectory)/uat_frontend.zip"

      # --- PROD BUILD ---
      - script: npx vite build --mode production
        displayName: "Vite Build: PROD"
        workingDirectory: "frontend"

      - task: ArchiveFiles@2
        displayName: "Zip PROD Dist"
        inputs:
          rootFolderOrFile: "frontend/dist"
          includeRootFolder: false
          archiveType: "zip"
          archiveFile: "$(Build.ArtifactStagingDirectory)/prod_frontend.zip"

      # Publish both zips in one artifact container
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: frontend_pkgs

  - deployment: DeployToIIS
    dependsOn: Build
    environment:
      name: "Win16a"
      resourceName: "WIN16A"
      resourceType: virtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: frontend_pkgs

            # Deploy UAT to /wwwroot
            - task: IISWebAppDeploymentOnMachineGroup@0
              displayName: "Deploy to wwwroot (UAT)"
              inputs:
                WebSiteName: "TallyJv4-UAT"
                Package: "$(Pipeline.Workspace)/frontend_pkgs/uat_frontend.zip"
                TakeAppOfflineFlag: true
                VirtualApplication: "wwwroot-uat"

            # Deploy PROD to /wwwroot-prod
            - task: IISWebAppDeploymentOnMachineGroup@0
              displayName: "Deploy to wwwroot-prod (Staged Prod)"
              inputs:
                WebSiteName: "TallyJv4-UAT"
                Package: "$(Pipeline.Workspace)/frontend_pkgs/prod_frontend.zip"
                TakeAppOfflineFlag: false # No need to take app offline for a non-active folder
                VirtualApplication: "wwwroot-prod"
