import fs from "fs";
import path from "path";
const dir = "dist/assets";
const f = "locale-fr-Db_fbhfx.js";
const p = path.join(dir, f);
const content = fs.readFileSync(p, "utf8");
console.log("Size:", content.length);
console.log("Prefix:", content.slice(0, 120));
console.log("Suffix:", content.slice(-120));
console.log("Has default export?", /export\s+default|export\{[^}]*default/.test(content));
console.log("Has 'as default'?", /as default/.test(content));
console.log("Has var e= ?", /var e=/.test(content));
