trigger:
  branches:
    include:
    - deploy
  paths:
    include:
    - backend/*  # Only trigger if files in this folder change
    exclude:
    - frontend/* # Explicitly ignore frontend changes
    
pool:
  vmImage: 'windows-latest'

variables:
  solution: '*.sln' 
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# This step usually requires a Deployment Group; 
# if this is where it's failing, the artifact below will show you why.
- task: IISWebAppDeploymentOnMachineGroup@0
  inputs:
    WebSiteName: 'TallyJv4-UAT'
    Package: '$(build.artifactStagingDirectory)\WebApp.zip'
    TakeAppOfflineFlag: true

# THE DEBUG STEP
- task: PublishPipelineArtifact@1
  displayName: 'Download Workspace for Inspection'
  condition: always() 
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'DebugWorkspace'
    publishLocation: 'pipeline'
