// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TallyJ4.EF.Context;

#nullable disable

namespace TallyJ4.EF.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.Ballot", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_RowId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<string>("BallotCode")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("_BallotCode")
                        .HasComputedColumnSql("([ComputerCode]+CONVERT([varchar],[BallotNumAtComputer],(0)))", true);

                    b.Property<Guid>("BallotGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BallotNumAtComputer")
                        .HasColumnType("int");

                    b.Property<string>("ComputerCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<Guid>("LocationGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("_RowVersion");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Teller1")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Teller2")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("RowId");

                    b.HasIndex(new[] { "BallotGuid" }, "IX_Ballot")
                        .IsUnique();

                    b.HasIndex(new[] { "ComputerCode" }, "IX_Ballot_Code");

                    b.HasIndex(new[] { "LocationGuid" }, "IX_Ballot_Location");

                    b.ToTable("Ballots");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.Election", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_RowId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<string>("CanReceive")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("CanVote")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Convenor")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomMethods")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateOfElection")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid>("ElectionGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(CONVERT([uniqueidentifier],CONVERT([binary](10),newid(),(0))+CONVERT([binary](6),getdate(),(0)),(0)))");

                    b.Property<string>("ElectionMode")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ElectionPasscode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ElectionType")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("EmailFromAddress")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("EmailFromName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailSubject")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("EmailText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HidePreBallotPages")
                        .HasColumnType("bit");

                    b.Property<int?>("LastEnvNum")
                        .HasColumnType("int");

                    b.Property<Guid?>("LinkedElectionGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LinkedElectionKind")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<bool?>("ListForPublic")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ListedForPublicAsOf")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("MaskVotingMethod")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("NumberExtra")
                        .HasColumnType("int");

                    b.Property<int?>("NumberToElect")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OnlineAnnounced")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("OnlineCloseIsEstimate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("OnlineSelectionProcess")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime?>("OnlineWhenClose")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("OnlineWhenOpen")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("OwnerLoginId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("_RowVersion");

                    b.Property<bool?>("ShowAsTest")
                        .HasColumnType("bit");

                    b.Property<bool?>("ShowFullReport")
                        .HasColumnType("bit");

                    b.Property<string>("SmsText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TallyStatus")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<bool?>("UseCallInButton")
                        .HasColumnType("bit");

                    b.Property<string>("VotingMethods")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("RowId");

                    b.HasIndex(new[] { "ElectionGuid" }, "IX_Election")
                        .IsUnique();

                    b.ToTable("Elections");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.ImportFile", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_RowId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<int?>("CodePage")
                        .HasColumnType("int");

                    b.Property<string>("ColumnsToRead")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Contents")
                        .HasColumnType("image");

                    b.Property<Guid>("ElectionGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("FileSize")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("(datalength([Contents]))", false);

                    b.Property<string>("FileType")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("FirstDataRow")
                        .HasColumnType("int");

                    b.Property<bool?>("HasContent")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bit")
                        .HasComputedColumnSql("(CONVERT([bit],case when [Contents] IS NULL then (0) else (1) end,(0)))", false);

                    b.Property<DateTime?>("ImportTime")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<string>("Messages")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProcessingStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UploadTime")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.HasKey("RowId");

                    b.HasIndex("ElectionGuid");

                    b.ToTable("ImportFiles");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.JoinElectionUser", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_RowId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<Guid>("ElectionGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InviteEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("InviteWhen")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Role")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RowId");

                    b.HasIndex(new[] { "ElectionGuid" }, "IX_JoinElectionUser_ElectionGuid");

                    b.HasIndex(new[] { "UserId" }, "IX_JoinElectionUser_UserId");

                    b.ToTable("JoinElectionUsers");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.Location", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_RowId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<int?>("BallotsCollected")
                        .HasColumnType("int");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("ElectionGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Lat")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("LocationGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Long")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("TallyStatus")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("RowId")
                        .HasName("PK_VotingLocation");

                    b.HasIndex(new[] { "LocationGuid" }, "IX_Location")
                        .IsUnique();

                    b.HasIndex(new[] { "ElectionGuid" }, "IX_Location_Election");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.Log", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_RowId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<DateTime>("AsOf")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ComputerCode")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Details")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid?>("ElectionGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HostAndVersion")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid?>("LocationGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VoterId")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("RowId");

                    b.HasIndex(new[] { "AsOf" }, "IX__Log");

                    b.HasIndex(new[] { "ElectionGuid", "LocationGuid" }, "nci_msft_1__Log_154BF30FBBDD3CC74014282844F74DFE");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.Message", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_RowId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<DateTime>("AsOf")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ElectionGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("_RowVersion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("RowId");

                    b.HasIndex("ElectionGuid");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.OnlineVoter", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_RowId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmailCodes")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("OtherInfo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("VerifyAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VerifyAttemptsStart")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("VerifyCode")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime?>("VerifyCodeDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("VoterId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("VoterIdType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("E");

                    b.Property<DateTime?>("WhenLastLogin")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("WhenRegistered")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("RowId");

                    b.HasIndex(new[] { "VoterId" }, "IX_OnlineVoter_Id")
                        .IsUnique();

                    b.ToTable("OnlineVoters");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.OnlineVotingInfo", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_RowId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<Guid>("ElectionGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HistoryStatus")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ListPool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("NotifiedAboutOpening")
                        .HasColumnType("bit");

                    b.Property<Guid>("PersonGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("PoolLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("WhenBallotCreated")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("WhenStatus")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("RowId");

                    b.HasIndex(new[] { "ElectionGuid", "PersonGuid" }, "IX_OnlineVotingInfo_ElectionPerson");

                    b.HasIndex(new[] { "PersonGuid" }, "IX_OnlineVotingInfo_Person");

                    b.ToTable("OnlineVotingInfos");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.Person", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_RowId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<string>("AgeGroup")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Area")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BahaiId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<bool?>("CanReceiveVotes")
                        .HasColumnType("bit");

                    b.Property<bool?>("CanVote")
                        .HasColumnType("bit");

                    b.Property<string>("CombinedInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CombinedInfoAtStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CombinedSoundCodes")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("ElectionGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("EnvNum")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Flags")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(461)
                        .HasColumnType("nvarchar(461)")
                        .HasColumnName("_FullName")
                        .HasComputedColumnSql("((((([LastName]+coalesce((' ['+nullif([OtherLastNames],''))+']',''))+', ')+coalesce([FirstName],''))+coalesce((' ['+nullif([OtherNames],''))+']',''))+coalesce((' ('+nullif([OtherInfo],''))+')',''))", true);

                    b.Property<string>("FullNameFl")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(460)
                        .HasColumnType("nvarchar(460)")
                        .HasColumnName("_FullNameFL")
                        .HasComputedColumnSql("((((coalesce([FirstName]+' ','')+[LastName])+coalesce((' ['+nullif([OtherNames],''))+']',''))+coalesce((' ['+nullif([OtherLastNames],''))+']',''))+coalesce((' ('+nullif([OtherInfo],''))+')',''))", true);

                    b.Property<bool?>("HasOnlineBallot")
                        .HasColumnType("bit");

                    b.Property<Guid?>("IneligibleReasonGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KioskCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OtherInfo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OtherLastNames")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OtherNames")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PersonGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Phone")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<DateTime?>("RegistrationTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("_RowVersion");

                    b.Property<long?>("RowVersionInt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("_RowVersionInt")
                        .HasComputedColumnSql("(CONVERT([bigint],[_RowVersion],(0)))", false);

                    b.Property<string>("Teller1")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Teller2")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("UnitName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("VotingLocationGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VotingMethod")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.HasKey("RowId");

                    b.HasIndex(new[] { "ElectionGuid" }, "IX_Person");

                    b.HasIndex(new[] { "ElectionGuid", "FullName" }, "IX_PersonElection");

                    b.HasIndex(new[] { "ElectionGuid", "Email" }, "IX_PersonEmail")
                        .IsUnique()
                        .HasFilter("([Email] IS NOT NULL AND [Email]<>'')");

                    b.HasIndex(new[] { "ElectionGuid", "Phone" }, "IX_PersonPhone")
                        .IsUnique()
                        .HasFilter("([Phone] IS NOT NULL AND [Phone]<>'')");

                    b.HasIndex(new[] { "PersonGuid" }, "IX_Person_1")
                        .IsUnique();

                    b.HasIndex(new[] { "CanVote", "IneligibleReasonGuid" }, "IX_Person_CanVote");

                    b.HasIndex(new[] { "ElectionGuid" }, "nci_msft_Person_22A77D9DC21D83B4582C43E94A27236D");

                    b.ToTable("People");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.Result", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_RowId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<bool?>("CloseToNext")
                        .HasColumnType("bit");

                    b.Property<bool?>("CloseToPrev")
                        .HasColumnType("bit");

                    b.Property<Guid>("ElectionGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("ForceShowInOther")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTieResolved")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTied")
                        .HasColumnType("bit");

                    b.Property<Guid>("PersonGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int?>("RankInExtra")
                        .HasColumnType("int");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<int?>("TieBreakCount")
                        .HasColumnType("int");

                    b.Property<int?>("TieBreakGroup")
                        .HasColumnType("int");

                    b.Property<bool?>("TieBreakRequired")
                        .HasColumnType("bit");

                    b.Property<int?>("VoteCount")
                        .HasColumnType("int");

                    b.HasKey("RowId");

                    b.HasIndex("PersonGuid");

                    b.HasIndex(new[] { "ElectionGuid" }, "IX_Result_Election");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.ResultSummary", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_RowId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<int?>("BallotsNeedingReview")
                        .HasColumnType("int");

                    b.Property<int?>("BallotsReceived")
                        .HasColumnType("int");

                    b.Property<int?>("CalledInBallots")
                        .HasColumnType("int");

                    b.Property<int?>("Custom1Ballots")
                        .HasColumnType("int");

                    b.Property<int?>("Custom2Ballots")
                        .HasColumnType("int");

                    b.Property<int?>("Custom3Ballots")
                        .HasColumnType("int");

                    b.Property<int?>("DroppedOffBallots")
                        .HasColumnType("int");

                    b.Property<Guid>("ElectionGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ImportedBallots")
                        .HasColumnType("int");

                    b.Property<int?>("InPersonBallots")
                        .HasColumnType("int");

                    b.Property<int?>("MailedInBallots")
                        .HasColumnType("int");

                    b.Property<int?>("NumEligibleToVote")
                        .HasColumnType("int");

                    b.Property<int?>("NumVoters")
                        .HasColumnType("int");

                    b.Property<int?>("OnlineBallots")
                        .HasColumnType("int");

                    b.Property<string>("ResultType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<int?>("SpoiledBallots")
                        .HasColumnType("int");

                    b.Property<int?>("SpoiledManualBallots")
                        .HasColumnType("int");

                    b.Property<int?>("SpoiledVotes")
                        .HasColumnType("int");

                    b.Property<int?>("TotalVotes")
                        .HasColumnType("int");

                    b.Property<bool?>("UseOnReports")
                        .HasColumnType("bit");

                    b.HasKey("RowId");

                    b.HasIndex(new[] { "ElectionGuid" }, "Ix_ResultSummary_Election");

                    b.ToTable("ResultSummaries");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.ResultTie", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_RowId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<Guid>("ElectionGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<int>("NumInTie")
                        .HasColumnType("int");

                    b.Property<int>("NumToElect")
                        .HasColumnType("int");

                    b.Property<int>("TieBreakGroup")
                        .HasColumnType("int");

                    b.Property<bool?>("TieBreakRequired")
                        .HasColumnType("bit");

                    b.HasKey("RowId");

                    b.HasIndex(new[] { "ElectionGuid", "TieBreakGroup" }, "IX_ResultTie")
                        .IsUnique();

                    b.ToTable("ResultTies");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.SmsLog", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_RowId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<Guid?>("ElectionGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ErrorCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("PersonGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("SentDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("SmsSid")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.HasKey("RowId");

                    b.HasIndex(new[] { "SmsSid" }, "IX_SmsLog");

                    b.HasIndex(new[] { "ElectionGuid", "LastDate" }, "IX_SmsLog_Election_Date")
                        .IsDescending(false, true);

                    b.ToTable("SmsLogs");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.Teller", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_RowId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<Guid>("ElectionGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsHeadTeller")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("_RowVersion");

                    b.Property<string>("UsingComputerCode")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.HasKey("RowId");

                    b.HasIndex(new[] { "ElectionGuid", "Name" }, "IX_Teller")
                        .IsUnique();

                    b.ToTable("Tellers");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.TwoFactorToken", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_RowId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("_RowVersion");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TokenGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(CONVERT([uniqueidentifier],CONVERT([binary](10),newid(),(0))+CONVERT([binary](6),getdate(),(0)),(0)))");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RowId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TwoFactorToken");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.Vote", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_RowId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<Guid>("BallotGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InvalidReasonGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OnlineVoteRaw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonCombinedInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PersonGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PositionOnBallot")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("_RowVersion");

                    b.Property<int?>("SingleNameElectionCount")
                        .HasColumnType("int");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("RowId");

                    b.HasIndex(new[] { "BallotGuid", "PositionOnBallot" }, "IX_VoteBallot");

                    b.HasIndex(new[] { "PersonGuid" }, "IX_VotePerson");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("TallyJ4.EF.Identity.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AuthMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TallyJ4.EF.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TallyJ4.EF.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TallyJ4.EF.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TallyJ4.EF.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.Ballot", b =>
                {
                    b.HasOne("TallyJ4.Domain.Entities.Location", "Location")
                        .WithMany("Ballots")
                        .HasForeignKey("LocationGuid")
                        .HasPrincipalKey("LocationGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Ballot_Location1");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.ImportFile", b =>
                {
                    b.HasOne("TallyJ4.Domain.Entities.Election", "Election")
                        .WithMany("ImportFiles")
                        .HasForeignKey("ElectionGuid")
                        .HasPrincipalKey("ElectionGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ImportFile_Election");

                    b.Navigation("Election");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.JoinElectionUser", b =>
                {
                    b.HasOne("TallyJ4.Domain.Entities.Election", "Election")
                        .WithMany("JoinElectionUsers")
                        .HasForeignKey("ElectionGuid")
                        .HasPrincipalKey("ElectionGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_JoinElectionUser_Election");

                    b.Navigation("Election");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.Location", b =>
                {
                    b.HasOne("TallyJ4.Domain.Entities.Election", "Election")
                        .WithMany("Locations")
                        .HasForeignKey("ElectionGuid")
                        .HasPrincipalKey("ElectionGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Location_Election");

                    b.Navigation("Election");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.Message", b =>
                {
                    b.HasOne("TallyJ4.Domain.Entities.Election", "Election")
                        .WithMany("Messages")
                        .HasForeignKey("ElectionGuid")
                        .HasPrincipalKey("ElectionGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Message_Election");

                    b.Navigation("Election");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.Person", b =>
                {
                    b.HasOne("TallyJ4.Domain.Entities.Election", "Election")
                        .WithMany("People")
                        .HasForeignKey("ElectionGuid")
                        .HasPrincipalKey("ElectionGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Person_Election");

                    b.Navigation("Election");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.Result", b =>
                {
                    b.HasOne("TallyJ4.Domain.Entities.Election", "Election")
                        .WithMany("Results")
                        .HasForeignKey("ElectionGuid")
                        .HasPrincipalKey("ElectionGuid")
                        .IsRequired()
                        .HasConstraintName("FK_Result_Election");

                    b.HasOne("TallyJ4.Domain.Entities.Person", "Person")
                        .WithMany("Results")
                        .HasForeignKey("PersonGuid")
                        .HasPrincipalKey("PersonGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Result_Person");

                    b.Navigation("Election");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.ResultSummary", b =>
                {
                    b.HasOne("TallyJ4.Domain.Entities.Election", "Election")
                        .WithMany("ResultSummaries")
                        .HasForeignKey("ElectionGuid")
                        .HasPrincipalKey("ElectionGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ResultSummary_Election1");

                    b.Navigation("Election");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.ResultTie", b =>
                {
                    b.HasOne("TallyJ4.Domain.Entities.Election", "Election")
                        .WithMany("ResultTies")
                        .HasForeignKey("ElectionGuid")
                        .HasPrincipalKey("ElectionGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ResultTie_Election");

                    b.Navigation("Election");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.Teller", b =>
                {
                    b.HasOne("TallyJ4.Domain.Entities.Election", "Election")
                        .WithMany("Tellers")
                        .HasForeignKey("ElectionGuid")
                        .HasPrincipalKey("ElectionGuid")
                        .IsRequired()
                        .HasConstraintName("FK_Teller_Election");

                    b.Navigation("Election");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.TwoFactorToken", b =>
                {
                    b.HasOne("TallyJ4.EF.Identity.AppUser", null)
                        .WithOne("TwoFactorToken")
                        .HasForeignKey("TallyJ4.Domain.Entities.TwoFactorToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.Vote", b =>
                {
                    b.HasOne("TallyJ4.Domain.Entities.Ballot", "Ballot")
                        .WithMany("Votes")
                        .HasForeignKey("BallotGuid")
                        .HasPrincipalKey("BallotGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Vote_Ballot");

                    b.HasOne("TallyJ4.Domain.Entities.Person", "Person")
                        .WithMany("Votes")
                        .HasForeignKey("PersonGuid")
                        .HasPrincipalKey("PersonGuid")
                        .HasConstraintName("FK_Vote_Person1");

                    b.Navigation("Ballot");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.Ballot", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.Election", b =>
                {
                    b.Navigation("ImportFiles");

                    b.Navigation("JoinElectionUsers");

                    b.Navigation("Locations");

                    b.Navigation("Messages");

                    b.Navigation("People");

                    b.Navigation("ResultSummaries");

                    b.Navigation("ResultTies");

                    b.Navigation("Results");

                    b.Navigation("Tellers");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.Location", b =>
                {
                    b.Navigation("Ballots");
                });

            modelBuilder.Entity("TallyJ4.Domain.Entities.Person", b =>
                {
                    b.Navigation("Results");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("TallyJ4.EF.Identity.AppUser", b =>
                {
                    b.Navigation("TwoFactorToken");
                });
#pragma warning restore 612, 618
        }
    }
}
